(function(a){function A(f,d,c,b){b={data:b||b===0||b===false?b:d?d.data:{},_wrap:d?d._wrap:null,tmpl:null,parent:d||null,nodes:[],calls:G,nest:H,wrap:o,html:K,update:e};f&&a.extend(b,f,{nodes:[],parent:d});if(c){b.tmpl=c;b._ctnt=b._ctnt||b.tmpl(a,b);b.key=++s;(x.length?m:j)[s]=b}return b}function y(f,d,c){var b;c=c?a.map(c,function(l){return typeof l==="string"?f.key?l.replace(/(<\w+)(?=[\s>])(?![^>]*_tmplitem)([^>]*)/g,"$1 "+i+'="'+f.key+'" $2'):l:y(l,f,l._ctnt)}):f;if(d)return c;c=c.join("");c.replace(/^\s*([^<\s][^<]*)?(<[\w\W]+>)([^>]*[^>\s])?\s*$/,
function(l,k,n,t){b=a(n).get();u(b);if(k)b=D(k).concat(b);if(t)b=b.concat(D(t))});return b?b:D(c)}function D(f){var d=document.createElement("div");d.innerHTML=f;return a.makeArray(d.childNodes)}function I(f){return new Function("jQuery","$item","var $=jQuery,call,__=[],$data=$item.data;with($data){__.push('"+a.trim(f).replace(/([\\'])/g,"\\$1").replace(/[\r\t\n]/g," ").replace(/\$\{([^\}]*)\}/g,"{{= $1}}").replace(/\{\{(\/?)(\w+|.)(?:\(((?:[^\}]|\}(?!\}))*?)?\))?(?:\s+(.*?)?)?(\(((?:[^\}]|\}(?!\}))*?)\))?\s*\}\}/g,
function(d,c,b,l,k,n,t){d=a.tmpl.tag[b];if(!d)throw"Unknown template tag: "+b;b=d._default||[];if(n&&!/\w$/.test(k)){k+=n;n=""}if(k){k=B(k);t=t?","+B(t)+")":n?")":"";t=n?k.indexOf(".")>-1?k+B(n):"("+k+").call($item"+t:k;n=n?t:"(typeof("+k+")==='function'?("+k+").call($item):("+k+"))"}else n=t=b.$1||"null";l=B(l);return"');"+d[c?"close":"open"].split("$notnull_1").join(k?"typeof("+k+")!=='undefined' && ("+k+")!=null":"true").split("$1a").join(n).split("$1").join(t).split("$2").join(l||b.$2||"")+"__.push('"})+
"');}return __;")}function E(f,d){f._wrap=y(f,true,a.isArray(d)?d:[h.test(d)?d:a(d).html()]).join("")}function B(f){return f?f.replace(/\\'/g,"'").replace(/\\\\/g,"\\"):null}function u(f){function d(C){function M(L){L+=c;r=k[L]=k[L]||A(r,j[r.parent.key+c]||r.parent)}var z,w=C,r,J;if(J=C.getAttribute(i)){for(;w.parentNode&&(w=w.parentNode).nodeType===1&&!(z=w.getAttribute(i)););if(z!==J){w=w.parentNode?w.nodeType===11?0:w.getAttribute(i)||0:0;if(!(r=j[J])){r=m[J];r=A(r,j[w]||m[w]);r.key=++s;j[s]=r}v&&
M(J)}C.removeAttribute(i)}else if(v&&(r=a.data(C,"tmplItem"))){M(r.key);j[r.key]=r;w=(w=a.data(C.parentNode,"tmplItem"))?w.key:0}if(r){for(z=r;z&&z.key!=w;){z.nodes.push(C);z=z.parent}delete r._ctnt;delete r._wrap;a.data(C,"tmplItem",r)}}var c="_"+v,b,l,k={},n,t,F;n=0;for(t=f.length;n<t;n++)if((b=f[n]).nodeType===1){l=b.getElementsByTagName("*");for(F=l.length-1;F>=0;F--)d(l[F]);d(b)}}function G(f,d,c,b){if(!f)return x.pop();x.push({_:f,tmpl:d,item:this,data:c,options:b})}function H(f,d,c){return a.tmpl(a.template(f),
d,c,this)}function o(f,d){var c=f.options||{};c.wrapped=d;return a.tmpl(a.template(f.tmpl),f.data,c,f.item)}function K(f,d){var c=this._wrap;return a.map(a(a.isArray(c)?c.join(""):c).filter(f||"*"),function(b){if(d)b=b.innerText||b.textContent;else{var l;if(!(l=b.outerHTML)){l=document.createElement("div");l.appendChild(b.cloneNode(true));l=l.innerHTML}b=l}return b})}function e(){var f=this.nodes;a.tmpl(null,null,null,this).insertBefore(f[0]);a(f).remove()}var g=a.fn.domManip,i="_tmplitem",h=/^[^<]*(<[\w\W]+>)[^>]*$|\{\{\! /,
j={},m={},p,q={key:0,data:{}},s=0,v=0,x=[];a.each({appendTo:"append",prependTo:"prepend",insertBefore:"before",insertAfter:"after",replaceAll:"replaceWith"},function(f,d){a.fn[f]=function(c){var b=[];c=a(c);var l,k,n;l=this.length===1&&this[0].parentNode;p=j||{};if(l&&l.nodeType===11&&l.childNodes.length===1&&c.length===1){c[d](this[0]);b=this}else{k=0;for(n=c.length;k<n;k++){v=k;l=(k>0?this.clone(true):this).get();a(c[k])[d](l);b=b.concat(l)}v=0;b=this.pushStack(b,f,c.selector)}c=p;p=null;a.tmpl.complete(c);
return b}});a.fn.extend({tmpl:function(f,d,c){return a.tmpl(this[0],f,d,c)},tmplItem:function(){return a.tmplItem(this[0])},template:function(f){return a.template(f,this[0])},domManip:function(f,d,c){if(f[0]&&a.isArray(f[0])){for(var b=a.makeArray(arguments),l=f[0],k=l.length,n=0,t;n<k&&!(t=a.data(l[n++],"tmplItem")););if(t&&v)b[2]=function(F){a.tmpl.afterManip(this,F,c)};g.apply(this,b)}else g.apply(this,arguments);v=0;p||a.tmpl.complete(j);return this}});a.extend({tmpl:function(f,d,c,b){var l=!b;
if(l){b=q;f=a.template[f]||a.template(null,f);m={}}else if(!f){f=b.tmpl;j[b.key]=b;b.nodes=[];b.wrapped&&E(b,b.wrapped);return a(y(b,null,b.tmpl(a,b)))}if(!f)return[];if(typeof d==="function")d=d.call(b||{});c&&c.wrapped&&E(c,c.wrapped);d=a.isArray(d)?a.map(d,function(k){return k?A(c,b,f,k):null}):[A(c,b,f,d)];return l?a(y(b,null,d)):d},tmplItem:function(f){var d;if(f instanceof a)f=f[0];for(;f&&f.nodeType===1&&!(d=a.data(f,"tmplItem"))&&(f=f.parentNode););return d||q},template:function(f,d){if(d){if(typeof d===
"string")d=I(d);else if(d instanceof a)d=d[0]||{};if(d.nodeType)d=a.data(d,"tmpl")||a.data(d,"tmpl",I(d.innerHTML));return typeof f==="string"?a.template[f]=d:d}return f?typeof f!=="string"?a.template(null,f):a.template[f]||a.template(null,h.test(f)?f:a(f)):null},encode:function(f){return(""+f).split("<").join("&lt;").split(">").join("&gt;").split('"').join("&#34;").split("'").join("&#39;")}});a.extend(a.tmpl,{tag:{tmpl:{_default:{$2:"null"},open:"if($notnull_1){__=__.concat($item.nest($1,$2));}"},
wrap:{_default:{$2:"null"},open:"$item.calls(__,$1,$2);__=[];",close:"call=$item.calls();__=call._.concat($item.wrap(call,__));"},each:{_default:{$2:"$index, $value"},open:"if($notnull_1){$.each($1a,function($2){with(this){",close:"}});}"},"if":{open:"if(($notnull_1) && $1a){",close:"}"},"else":{_default:{$1:"true"},open:"}else if(($notnull_1) && $1a){"},html:{open:"if($notnull_1){__.push($1a);}"},"=":{_default:{$1:"$data"},open:"if($notnull_1){__.push($.encode($1a));}"},"!":{open:""}},complete:function(){j=
{}},afterManip:function(f,d,c){var b=d.nodeType===11?a.makeArray(d.childNodes):d.nodeType===1?[d]:[];c.call(f,d);u(b);v++}})})(jQuery);
(function(){var a,A,y,D,I,E,B,u,G,H,o,K=function(e,g){return function(){return e.apply(g,arguments)}};o=this;a=o.jQuery;o.pte=u=u||{};(function(e){return e.fixThickbox=function(g){var i,h,j,m;i=g.jQuery;if(!(i===null||g.frames.length<1)){log("===== FIXING THICKBOX =====");m=o.options.pte_tb_width+30;j=o.options.pte_tb_height+38;h=i("#TB_window");if(!(h.width()>=m&&h.height()>=j)){log("THICKBOX: "+h.width()+" x "+h.height());h.css({"margin-left":0-m/2,width:m,height:j}).children("iframe").css({width:m});
return g.setTimeout(function(){if(!(i("iframe",h).height()>j)){i("iframe",h).css({height:j});log("THICKBOX: "+h.width()+" x "+h.height());return true}},1E3)}}}})(u);H=function(e){return{}.toString.call(e).match(/\s([a-z|A-Z]+)/)[1].toLowerCase()};A=function(){function e(g){this.message=g;this.date=new Date}e.prototype.toString=function(){var g,i,h,j,m,p,q;p=function(s,v){for(;(""+s).length<v;)s="0"+s;return s};h=this.date;q=p(h.getUTCFullYear(),4);i=p(h.getUTCMonth()+1,2);g=p(h.getUTCDate(),2);j=
p(h.getUTCHours(),2);m=p(h.getUTCMinutes(),2);p=p(h.getUTCSeconds(),2);switch(H(this.message)){case "string":h=this.message;break;default:h=a.toJSON(this.message)}return""+q+i+g+" "+j+":"+m+":"+p+" - ["+H(this.message)+"] "+h};return e}();(function(e){e.messages=[];e.log=function(g){if(!o.options.pte_debug)return true;try{e.messages.push(new A(g));console.log(g);a("#pte-log-messages textarea").filter(":visible").val(e.formatLog())}catch(i){}};e.formatLog=function(){var g,i,h,j,m;g="";m=e.messages;
h=0;for(j=m.length;h<j;h++){i=m[h];g+=""+i+"\n"}return g};e.parseServerLog=function(g){var i,h,j;log("===== SERVER LOG =====");if((g!=null?g.length:void 0)!=null&&g.length>0){h=0;for(j=g.length;h<j;h++){i=g[h];log(i)}}return true};e.sendToPastebin=function(g){return a.ajax({url:"http://dpastey.appspot.com/",data:{title:"PostThumbnailEditor Log",content:g,lexer:"text",format:"json",expire_options:"2592000"},dataType:"json",global:false,type:"POST",error:function(i,h,j){a("#pte-log").fadeOut("900");
alert(objectL10n.pastebin_create_error);log(i);log(h);return log(j)},success:function(i){a("#pte-log").fadeOut("900");return prompt(objectL10n.pastebin_url,i.url)}})};return true})(u);o.log=u.log;a(document).ready(function(e){e("#test").click(function(g){g.stopImmediatePropagation();return true});e("#pastebin").click(function(){return u.sendToPastebin(u.formatLog())});e("#clear-log").click(function(){u.messages=[];return e("#pte-log-messages textarea").val(u.formatLog())});e("#close-log").click(function(){return e("#pte-log").fadeOut("900")});
e("#pte-log-tools a").click(function(g){return g.preventDefault()});return e("body").delegate(".show-log-messages","click",function(g){g.preventDefault();e("#pte-log-messages textarea").val(u.formatLog());return e("#pte-log").fadeIn("900")})});(function(e){return e.admin=function(){var g,i,h,j,m,p;p="&TB_iframe=true&height="+o.options.pte_tb_height+"&width="+o.options.pte_tb_width;h=null;m=function(q){q=q||h||a("#attachment-id").val();return""+ajaxurl+"?action=pte_ajax&pte-action=launch&id="+q+p};
g=function(q){return a('<a class="thickbox" href="'+m(q)+'">'+objectL10n.PTE+"</a>")};i=function(q){log("Start PTE...");if(o.parent.frames.length>0){log("Modifying thickbox...");o.parent.tb_click();return q.stopPropagation()}};j=function(){var q;q=a("#imgedit-save-target-"+h);if((q!=null?q.size():void 0)<1){o.log("Edit Thumbnail Menu not visible, waiting for 300ms");o.setTimeout(j,300);return false}return q.append(g().click(i))};return function(){a(".media-item").each(function(q,s){var v;v=s.id.replace("media-item-",
"");return g(v).css({"font-size":".8em","margin-left":"5px"}).click(i).appendTo(a("tr.image-size th.label",s))});if(imageEdit.open!=null){imageEdit.oldopen=imageEdit.open;imageEdit.open=function(q,s){h=q;imageEdit.oldopen(q,s);return j()}}return true}()}})(u);y=function(){function e(g,i){this.fn=g;this.timeout=i;this.doFunc=K(this.doFunc,this);this.timer=null}e.prototype.doFunc=function(){o.clearTimeout(this.timer);this.timer=o.setTimeout(this.fn,this.timeout);return true};return e}();o.randomness=
function(){return Math.floor(Math.random()*1000001).toString(16)};o.debugTmpl=function(e){log("===== TEMPLATE DEBUG DATA FOLLOWS =====");log(e);return true};D=function(e){e={id:e,action:"pte_ajax","pte-action":"delete-images","pte-nonce":a("#pte-delete-nonce").val()};return a.ajax({url:ajaxurl,data:e,global:false,dataType:"json",success:I})};I=function(e){log("===== DELETE SUCCESSFUL, DATA DUMP FOLLOWS =====");log(e);return u.parseServerLog(e.log)};G=a({});a.fn.extend({move:function(e){e=a.extend({direction:"left",
speed:500,easing:"swing",toggle:true,callback:null,callbackargs:null},e);this.each(function(){var g=this;return G.queue(function(i){var h,j,m,p;h=a(g);j=e.direction==="left"?-1:1;p=h.css("left")==="0px"?a(o).width()*j:0;m=h.is(":visible");log([j,p,m]);if(m){h.animate({left:p},e.speed,e.easing);h.hide(0,i)}else h.show(0,function(){return a(this).animate({left:p},e.speed,e.easing,i)});return true})});e.callback!=null&&G.queue(function(g){if(e.callbackargs!=null){log("running callback with arguments");
e.callback.apply(this,e.callbackargs)}else{log("running callback with no arguments");e.callback.apply(this)}log("finished running callback");return g()});return this},moveRight:function(e){e=a.extend(e,{direction:"right"});return this.move(e)},moveLeft:function(e){e=a.extend(e,{direction:"left"});return this.move(e)}});o.goBack=function(e){e!=null&&e.preventDefault();a("#stage2").moveRight();a("#stage1").moveRight({callback:function(){D(a("#pte-post-id").val());return a("#stage2").html("")}});return true};
B=function(e,g){if(e===0)return g;for(;g>0;)if(e>g)e-=g;else g-=e;if(e<0||g<0)return null;return e};E=function(e,g){var i,h,j,m;i=g.crop;m=g.width;j=g.height;i=+i;m=+m;j=+j;h=B(m,j);if(i!=null&&i>0){i=null;if(m!=null&&m>0&&j!=null&&j>0)i=h!=null?""+m/h+":"+j/h:""+m+":"+j;if(e!=null&&i!=null&&i!==e)throw objectL10n.aspect_ratio_disabled;e=i}return e};u.functions={determineAspectRatio:E};(function(e){var g,i,h,j,m,p,q,s,v,x,f;e.editor=function(){q();h();f();i();j();m();g();p();return true};p=function(){var d,
c;d=a("#pte-loading");c=function(){d.hide();return true};a("#pte-preview").load(c);d.ajaxStart(function(){return a(this).fadeIn(200)}).ajaxStop(function(){return a(this).fadeOut(200)});o.setTimeout(c,2E3);return true};q=function(){var d;d=new y(function(){var c;log("===== REFLOW =====");e.fixThickbox(o.parent);c=a("#pte-sizes").offset();c=a(o).height()-c.top-2;a("#pte-sizes").height(c);log("WINDOW WIDTH: "+a(o).width());a("#stage2, #stage3").filter(":hidden").css({left:a(o).width()});return true},
100);a(o).resize(d.doFunc).load(d.doFunc);return true};h=function(){var d;d=function(c){c.delegate("tr","click",function(b){b.target.type!=="checkbox"&&a("input:checkbox",this).click();return true});return c.delegate("input:checkbox","click",function(){this.checked||a(this).is("input:checked")?a(this).parents("tr").first().removeClass("selected"):a(this).parents("tr").first().addClass("selected");return true})};d(a("#stage2"));return d(a("#stage1"))};x=null;v={keys:true,minWidth:3,minHeight:3,handles:true,
zIndex:1200,instance:true,onSelectEnd:function(d,c){return c.width&&c.width>0&&c.height&&c.height>0&&a(".pte-size").filter(":checked").size()>0?a("#pte-submit").removeAttr("disabled"):a("#pte-submit").attr("disabled",true)}};f=function(){return e.ias=x=a("#pte-image img").imgAreaSelect(v)};s=function(d){log("===== SETTING ASPECTRATIO: "+d+" =====");x.setOptions({aspectRatio:d});return x.update()};i=function(){var d,c;c=new y(function(){log("===== CHECK SUBMIT BUTTON =====");if(a(".pte-confirm").filter(":checked").size()>
0){log("ENABLE");a("#pte-confirm").removeAttr("disabled")}else{log("DISABLE");a("#pte-confirm").attr("disabled",true)}return true},50);d=new y(function(){var b;b=null;a("input.pte-size").filter(":checked").each(function(l,k){try{b=E(b,thumbnail_info[a(k).val()])}catch(n){b=null;b!==x.getOptions().aspectRatio&&alert(n);return false}return true});s(b);v.onSelectEnd(null,x.getSelection());return true},50);a.extend(e.functions,{pteVerifySubmitButtonHandler:c});a("input.pte-size").click(d.doFunc);return a(".pte-confirm").live("click",
function(){return c.doFunc()})};j=function(){var d;a("#pte-submit").click(function(){var c,b;b=x.getSelection();c=a("#pte-sizer").val();c={id:a("#pte-post-id").val(),action:"pte_ajax","pte-action":"resize-images","pte-sizes[]":a(".pte-size").filter(":checked").map(function(){return a(this).val()}).get(),x:Math.floor(b.x1/c),y:Math.floor(b.y1/c),w:Math.floor(b.width/c),h:Math.floor(b.height/c)};log("===== RESIZE-IMAGES =====");log(c);if(isNaN(c.x)||isNaN(c.y)||isNaN(c.w)||isNaN(c.h)){alert(objectL10n.crop_submit_data_error);
log("ERROR with submit_data and NaN's");return false}x.setOptions({hide:true,x1:0,y1:0,x2:0,y2:0});a("#pte-submit").attr("disabled",true);a.getJSON(ajaxurl,c,d);return true});return d=function(c){log("===== RESIZE-IMAGES SUCCESS =====");log(c);e.parseServerLog(c.log);if(c.error!=null&&c.thumbnails==null)alert(c.error);else{a("#stage1").moveLeft();a("#stage2").html(a("#stage2template").tmpl(c)).moveLeft({callback:e.functions.pteVerifySubmitButtonHandler.doFunc});return false}}};m=function(){var d;
a("#pte-confirm").live("click",function(){var c,b;b={};a("input.pte-confirm").filter(":checked").each(function(l,k){var n;n=a(k).val();return b[n]=a(k).parent().parent().find(".pte-file").val()});c={id:a("#pte-post-id").val(),action:"pte_ajax","pte-action":"confirm-images","pte-nonce":a("#pte-nonce").val(),"pte-confirm":b};log("===== CONFIRM-IMAGES =====");log(c);return a.getJSON(ajaxurl,c,d)});return d=function(c){log("===== CONFIRM-IMAGES SUCCESS =====");log(c);e.parseServerLog(c.log);a("#stage2").moveLeft();
a("#stage3").html(a("#stage3template").tmpl(c)).moveLeft();return false}};g=function(){var d,c;c=function(b){var l,k;b!=null&&b.preventDefault();b=(l=(k=b.data)!=null?k.selector:void 0)!=null?l:".pte-size";return a(b).filter(":checked").click()};d=function(b){var l,k;b!=null&&b.preventDefault();b=(l=b!=null?(k=b.data)!=null?k.selector:void 0:void 0)!=null?l:".pte-size";return a(b).not(":checked").click()};a("#pte-selectors .all").click(d);a("#pte-selectors .none").click(c).click();a("#stage2").delegate("#pte-stage2-selectors .all",
"click",{selector:".pte-confirm"},d);a("#stage2").delegate("#pte-stage2-selectors .none","click",{selector:".pte-confirm"},c);return true};return a.extend(e.functions,{iasSetAR:s})})(u)}).call(this);
