(function(a){function b(m,k,b,f){f={data:f||0===f||!1===f?f:k?k.data:{},_wrap:k?k._wrap:null,tmpl:null,parent:k||null,nodes:[],calls:p,nest:u,wrap:q,html:v,update:l};m&&a.extend(f,m,{nodes:[],parent:k});b&&(f.tmpl=b,f._ctnt=f._ctnt||f.tmpl(a,f),f.key=++w,(z.length?x:r)[w]=f);return f}function g(m,k,b){var f;b=b?a.map(b,function(a){return"string"===typeof a?m.key?a.replace(/(<\w+)(?=[\s>])(?![^>]*_tmplitem)([^>]*)/g,"$1 "+t+'="'+m.key+'" $2'):a:g(a,m,a._ctnt)}):m;if(k)return b;b=b.join("");b.replace(/^\s*([^<\s][^<]*)?(<[\w\W]+>)([^>]*[^>\s])?\s*$/,
function(b,m,k,d){f=a(k).get();n(f);m&&(f=e(m).concat(f));d&&(f=f.concat(e(d)))});return f?f:e(b)}function e(m){var b=document.createElement("div");b.innerHTML=m;return a.makeArray(b.childNodes)}function c(b){return new Function("jQuery","$item","var $=jQuery,call,__=[],$data=$item.data;with($data){__.push('"+a.trim(b).replace(/([\\'])/g,"\\$1").replace(/[\r\t\n]/g," ").replace(/\$\{([^\}]*)\}/g,"{{= $1}}").replace(/\{\{(\/?)(\w+|.)(?:\(((?:[^\}]|\}(?!\}))*?)?\))?(?:\s+(.*?)?)?(\(((?:[^\}]|\}(?!\}))*?)\))?\s*\}\}/g,
function(b,m,f,e,d,g,c){b=a.tmpl.tag[f];if(!b)throw"Unknown template tag: "+f;f=b._default||[];g&&!/\w$/.test(d)&&(d+=g,g="");d?(d=j(d),c=c?","+j(c)+")":g?")":"",c=g?-1<d.indexOf(".")?d+j(g):"("+d+").call($item"+c:d,g=g?c:"(typeof("+d+")==='function'?("+d+").call($item):("+d+"))"):g=c=f.$1||"null";e=j(e);return"');"+b[m?"close":"open"].split("$notnull_1").join(d?"typeof("+d+")!=='undefined' && ("+d+")!=null":"true").split("$1a").join(g).split("$1").join(c).split("$2").join(e||f.$2||"")+"__.push('"})+
"');}return __;")}function h(b,d){b._wrap=g(b,!0,a.isArray(d)?d:[A.test(d)?d:a(d).html()]).join("")}function j(a){return a?a.replace(/\\'/g,"'").replace(/\\\\/g,"\\"):null}function n(d){function e(d){function m(a){a+=g;c=h[a]=h[a]||b(c,r[c.parent.key+g]||c.parent)}var f,k=d,c,l;if(l=d.getAttribute(t)){for(;k.parentNode&&1===(k=k.parentNode).nodeType&&!(f=k.getAttribute(t)););if(f!==l){k=k.parentNode?11===k.nodeType?0:k.getAttribute(t)||0:0;if(!(c=r[l]))c=x[l],c=b(c,r[k]||x[k]),c.key=++w,r[w]=c;s&&
m(l)}d.removeAttribute(t)}else if(s&&(c=a.data(d,"tmplItem")))m(c.key),r[c.key]=c,k=(k=a.data(d.parentNode,"tmplItem"))?k.key:0;if(c){for(f=c;f&&f.key!=k;)f.nodes.push(d),f=f.parent;delete c._ctnt;delete c._wrap;a.data(d,"tmplItem",c)}}var g="_"+s,f,c,h={},l,p,j;l=0;for(p=d.length;l<p;l++)if(1===(f=d[l]).nodeType){c=f.getElementsByTagName("*");for(j=c.length-1;0<=j;j--)e(c[j]);e(f)}}function p(a,b,d,f){if(!a)return z.pop();z.push({_:a,tmpl:b,item:this,data:d,options:f})}function u(b,d,c){return a.tmpl(a.template(b),
d,c,this)}function q(b,d){var c=b.options||{};c.wrapped=d;return a.tmpl(a.template(b.tmpl),b.data,c,b.item)}function v(b,d){var c=this._wrap;return a.map(a(a.isArray(c)?c.join(""):c).filter(b||"*"),function(a){if(d)a=a.innerText||a.textContent;else{var b;if(!(b=a.outerHTML))b=document.createElement("div"),b.appendChild(a.cloneNode(!0)),b=b.innerHTML;a=b}return a})}function l(){var b=this.nodes;a.tmpl(null,null,null,this).insertBefore(b[0]);a(b).remove()}var d=a.fn.domManip,t="_tmplitem",A=/^[^<]*(<[\w\W]+>)[^>]*$|\{\{\! /,
r={},x={},y,B={key:0,data:{}},w=0,s=0,z=[];a.each({appendTo:"append",prependTo:"prepend",insertBefore:"before",insertAfter:"after",replaceAll:"replaceWith"},function(b,d){a.fn[b]=function(c){var f=[];c=a(c);var e,g,l;e=1===this.length&&this[0].parentNode;y=r||{};if(e&&11===e.nodeType&&1===e.childNodes.length&&1===c.length)c[d](this[0]),f=this;else{g=0;for(l=c.length;g<l;g++)s=g,e=(0<g?this.clone(!0):this).get(),a(c[g])[d](e),f=f.concat(e);s=0;f=this.pushStack(f,b,c.selector)}c=y;y=null;a.tmpl.complete(c);
return f}});a.fn.extend({tmpl:function(b,d,c){return a.tmpl(this[0],b,d,c)},tmplItem:function(){return a.tmplItem(this[0])},template:function(b){return a.template(b,this[0])},domManip:function(b,c,e,f){if(b[0]&&a.isArray(b[0])){for(var g=a.makeArray(arguments),l=b[0],t=l.length,h=0,p;h<t&&!(p=a.data(l[h++],"tmplItem")););p&&s&&(g[2]=function(b){a.tmpl.afterManip(this,b,e)});d.apply(this,g)}else d.apply(this,arguments);s=0;y||a.tmpl.complete(r);return this}});a.extend({tmpl:function(d,c,e,f){var l=
!f;if(l)f=B,d=a.template[d]||a.template(null,d),x={};else if(!d)return d=f.tmpl,r[f.key]=f,f.nodes=[],f.wrapped&&h(f,f.wrapped),a(g(f,null,f.tmpl(a,f)));if(!d)return[];"function"===typeof c&&(c=c.call(f||{}));e&&e.wrapped&&h(e,e.wrapped);c=a.isArray(c)?a.map(c,function(a){return a?b(e,f,d,a):null}):[b(e,f,d,c)];return l?a(g(f,null,c)):c},tmplItem:function(b){var d;for(b instanceof a&&(b=b[0]);b&&1===b.nodeType&&!(d=a.data(b,"tmplItem"))&&(b=b.parentNode););return d||B},template:function(b,d){return d?
("string"===typeof d?d=c(d):d instanceof a&&(d=d[0]||{}),d.nodeType&&(d=a.data(d,"tmpl")||a.data(d,"tmpl",c(d.innerHTML))),"string"===typeof b?a.template[b]=d:d):b?"string"!==typeof b?a.template(null,b):a.template[b]||a.template(null,A.test(b)?b:a(b)):null},encode:function(a){return(""+a).split("<").join("&lt;").split(">").join("&gt;").split('"').join("&#34;").split("'").join("&#39;")}});a.extend(a.tmpl,{tag:{tmpl:{_default:{$2:"null"},open:"if($notnull_1){__=__.concat($item.nest($1,$2));}"},wrap:{_default:{$2:"null"},
open:"$item.calls(__,$1,$2);__=[];",close:"call=$item.calls();__=call._.concat($item.wrap(call,__));"},each:{_default:{$2:"$index, $value"},open:"if($notnull_1){$.each($1a,function($2){with(this){",close:"}});}"},"if":{open:"if(($notnull_1) && $1a){",close:"}"},"else":{_default:{$1:"true"},open:"}else if(($notnull_1) && $1a){"},html:{open:"if($notnull_1){__.push($1a);}"},"=":{_default:{$1:"$data"},open:"if($notnull_1){__.push($.encode($1a));}"},"!":{open:""}},complete:function(){r={}},afterManip:function(b,
d,c){var e=11===d.nodeType?a.makeArray(d.childNodes):1===d.nodeType?[d]:[];c.call(b,d);n(e);s++}})})(jQuery);var $,pte,window;window=this;$=window.jQuery;window.pte=pte=pte||{};
(function(a){return a.fixThickbox=function(a){var g,e,c,h;g=a.jQuery;if(!(null===g||1>a.frames.length))if(log("===== FIXING THICKBOX ====="),h=window.options.pte_tb_width+30,c=window.options.pte_tb_height+38,e=g("#TB_window"),!(e.width()>=h&&e.height()>=c))return log("THICKBOX: "+e.width()+" x "+e.height()),e.css({"margin-left":0-h/2,width:h,height:c}).children("iframe").css({width:h}),a.setTimeout(function(){if(!(g("iframe",e).height()>c))return g("iframe",e).css({height:c}),log("THICKBOX: "+e.width()+
" x "+e.height()),!0},1E3)}})(pte);var Message,toType;toType=function(a){return{}.toString.call(a).match(/\s([a-z|A-Z]+)/)[1].toLowerCase()};
Message=function(){function a(a){this.message=a;this.date=new Date}a.prototype.toString=function(){var a,g,e,c,h,j,n;j=function(a,b){for(;(""+a).length<b;)a="0"+a;return a};e=this.date;n=j(e.getUTCFullYear(),4);g=j(e.getUTCMonth()+1,2);a=j(e.getUTCDate(),2);c=j(e.getUTCHours(),2);h=j(e.getUTCMinutes(),2);j=j(e.getUTCSeconds(),2);switch(toType(this.message)){case "string":e=this.message;break;default:e=$.toJSON(this.message)}return""+n+g+a+" "+c+":"+h+":"+j+" - ["+toType(this.message)+"] "+e};return a}();
(function(a){a.messages=[];a.log=function(b){if(!window.options.pte_debug)return!0;try{a.messages.push(new Message(b)),console.log(b),$("#pte-log-messages textarea").filter(":visible").val(a.formatLog())}catch(g){}};a.formatLog=function(){var b,g,e,c,h;b="";h=a.messages;e=0;for(c=h.length;e<c;e++)g=h[e],b+=""+g+"\n";return b};a.parseServerLog=function(a){var g,e,c;log("===== SERVER LOG =====");if(null!=(null!=a?a.length:void 0)&&0<a.length){e=0;for(c=a.length;e<c;e++)g=a[e],log(g)}return!0};a.sendToPastebin=
function(a){return $.ajax({url:"http://dpastey.appspot.com/",data:{title:"PostThumbnailEditor Log",content:a,lexer:"text",format:"json",expire_options:"2592000"},dataType:"json",global:!1,type:"POST",error:function(a,b,c){$("#pte-log").fadeOut("900");alert(objectL10n.pastebin_create_error);log(a);log(b);return log(c)},success:function(a){$("#pte-log").fadeOut("900");return prompt(objectL10n.pastebin_url,a.url)}})};return!0})(pte);window.log=pte.log;
$(document).ready(function(a){a("#test").click(function(a){a.stopImmediatePropagation();return!0});a("#pastebin").click(function(){return pte.sendToPastebin(pte.formatLog())});a("#clear-log").click(function(){pte.messages=[];return a("#pte-log-messages textarea").val(pte.formatLog())});a("#close-log").click(function(){return a("#pte-log").fadeOut("900")});a("#pte-log-tools a").click(function(a){return a.preventDefault()});return a("body").delegate(".show-log-messages","click",function(b){b.preventDefault();
a("#pte-log-messages textarea").val(pte.formatLog());return a("#pte-log").fadeIn("900")})});
(function(a){a.media=function(){var a;a=$("#tmpl-attachment-details").text();a=a.replace(/(<div class="compat-meta">)/,""+('<a target="_blank" href="'+ajaxurl+'?action=pte_ajax&pte-action=launch&id={{data.id}}">\n\t'+objectL10n.PTE+"\n</a>")+"\n$1");return $("#tmpl-attachment-details").text(a)};return a.admin=function(){var a,g,e,c,h,j;j="&TB_iframe=true&height="+window.options.pte_tb_height+"&width="+window.options.pte_tb_width;e=null;h=function(a){a=a||e||$("#attachment-id").val();return""+ajaxurl+
"?action=pte_ajax&pte-action=launch&id="+a+j};a=function(a){return $('<a class="thickbox" href="'+h(a)+'">'+objectL10n.PTE+"</a>")};g=function(a){log("Start PTE...");if(0<window.parent.frames.length)return log("Modifying thickbox..."),window.parent.tb_click(),a.stopPropagation()};c=function(){var h;h=$("#imgedit-save-target-"+e);return 1>(null!=h?h.size():void 0)?(window.log("Edit Thumbnail Menu not visible, waiting for 300ms"),window.setTimeout(c,300),!1):h.append(a().click(g))};var n;$(".media-item").each(function(c,
e){var h;h=e.id.replace("media-item-","");return a(h).css({"font-size":".8em","margin-left":"5px"}).click(g).appendTo($("tr.image-size th.label",e))});null!=imageEdit.open&&(imageEdit.oldopen=imageEdit.open,imageEdit.open=function(a,b){e=a;imageEdit.oldopen(a,b);return c()});n=$('p[id^="imgedit-save-target-"]');if(0<(null!=n?n.length:void 0))n=n[0].id.match(/imgedit-save-target-(\d+)/),null!=n[1]&&(e=n[1],c());return!0}})(pte);
var TimerFunc,deleteThumbs,deleteThumbsSuccessCallback,determineAspectRatio,gcd,pte_queue,__bind=function(a,b){return function(){return a.apply(b,arguments)}};TimerFunc=function(){function a(a,g){this.fn=a;this.timeout=g;this.doFunc=__bind(this.doFunc,this);this.timer=null}a.prototype.doFunc=function(){window.clearTimeout(this.timer);this.timer=window.setTimeout(this.fn,this.timeout);return!0};return a}();window.randomness=function(){return Math.floor(1000001*Math.random()).toString(16)};
window.debugTmpl=function(a){log("===== TEMPLATE DEBUG DATA FOLLOWS =====");log(a);return!0};deleteThumbs=function(a){a={id:a,action:"pte_ajax","pte-action":"delete-images","pte-nonce":$("#pte-delete-nonce").val()};return $.ajax({url:ajaxurl,data:a,global:!1,dataType:"json",success:deleteThumbsSuccessCallback})};deleteThumbsSuccessCallback=function(a){log("===== DELETE SUCCESSFUL, DATA DUMP FOLLOWS =====");log(a);return pte.parseServerLog(a.log)};pte_queue=$({});
$.fn.extend({move:function(a){a=$.extend({direction:"left",speed:500,easing:"swing",toggle:!0,callback:null,callbackargs:null},a);this.each(function(){var b=this;return pte_queue.queue(function(g){var e,c,h,j;e=$(b);c="left"===a.direction?-1:1;j="0px"===e.css("left")?$(window).width()*c:0;h=e.is(":visible");log([c,j,h]);h?(e.animate({left:j},a.speed,a.easing),e.hide(0,g)):e.show(0,function(){return $(this).animate({left:j},a.speed,a.easing,g)});return!0})});null!=a.callback&&pte_queue.queue(function(b){null!=
a.callbackargs?(log("running callback with arguments"),a.callback.apply(this,a.callbackargs)):(log("running callback with no arguments"),a.callback.apply(this));log("finished running callback");return b()});return this},moveRight:function(a){a=$.extend(a,{direction:"right"});return this.move(a)},moveLeft:function(a){a=$.extend(a,{direction:"left"});return this.move(a)}});
window.goBack=function(a){null!=a&&a.preventDefault();$("#stage2").moveRight();$("#stage1").moveRight({callback:function(){deleteThumbs($("#pte-post-id").val());return $("#stage2").html("")}});return!0};gcd=function(a,b){if(0===a)return b;for(;0<b;)a>b?a-=b:b-=a;return 0>a||0>b?null:a};
determineAspectRatio=function(a,b){var g,e,c,h;g=b.crop;h=b.width;c=b.height;g=+g;h=+h;c=+c;e=gcd(h,c);if(null!=g&&0<g){g=null;null!=h&&(0<h&&null!=c&&0<c)&&(g=null!=e?""+h/e+":"+c/e:""+h+":"+c);if(null!=a&&null!=g&&g!==a)throw objectL10n.aspect_ratio_disabled;a=g}return a};pte.functions={determineAspectRatio:determineAspectRatio};
(function(a){var b,g,e,c,h,j,n,p,u,q,v;a.editor=function(){n();e();v();g();c();h();b();j();return!0};j=function(){var a,d;a=$("#pte-loading");d=function(){a.hide();return!0};$("#pte-preview").load(d);a.ajaxStart(function(){return $(this).fadeIn(200)}).ajaxStop(function(){return $(this).fadeOut(200)});window.setTimeout(d,2E3);return!0};n=function(){var b;b=new TimerFunc(function(){var d;log("===== REFLOW =====");a.fixThickbox(window.parent);d=$("#pte-sizes").offset();d=$(window).height()-d.top-2;$("#pte-sizes").height(d);
log("WINDOW WIDTH: "+$(window).width());$("#stage2, #stage3").filter(":hidden").css({left:$(window).width()});return!0},100);$(window).resize(b.doFunc).load(b.doFunc);return!0};e=function(){var a;a=function(a){a.delegate("tr","click",function(a){"checkbox"!==a.target.type&&$("input:checkbox",this).click();return!0});return a.delegate("input:checkbox","click",function(){this.checked||$(this).is("input:checked")?$(this).parents("tr").first().removeClass("selected"):$(this).parents("tr").first().addClass("selected");
return!0})};a($("#stage2"));return a($("#stage1"))};q=null;u={keys:!0,minWidth:3,minHeight:3,handles:!0,zIndex:1200,instance:!0,onSelectEnd:function(a,d){if(d.width&&0<d.width&&d.height&&0<d.height&&0<$(".pte-size").filter(":checked").size())return log("DISABLING SUBMIT"),$("#pte-submit").removeAttr("disabled");log("ENABLING SUBMIT");return $("#pte-submit").attr("disabled",!0)}};v=function(){return a.ias=q=$("#pte-image img").imgAreaSelect(u)};p=function(a){log("===== SETTING ASPECTRATIO: "+a+" =====");
q.setOptions({aspectRatio:a});return q.update()};g=function(){var b,d;d=new TimerFunc(function(){log("===== CHECK SUBMIT BUTTON =====");0<$(".pte-confirm").filter(":checked").size()?(log("ENABLE"),$("#pte-confirm").removeAttr("disabled")):(log("DISABLE"),$("#pte-confirm").attr("disabled",!0));return!0},50);b=new TimerFunc(function(){var a;a=null;$("input.pte-size").filter(":checked").each(function(d,b){try{a=determineAspectRatio(a,thumbnail_info[$(b).val()])}catch(c){return a=null,a!==q.getOptions().aspectRatio&&
log("Setting Aspect Ratio to null"),!1}return!0});p(a);u.onSelectEnd(null,q.getSelection());return!0},50);$.extend(a.functions,{pteVerifySubmitButtonHandler:d});$("input.pte-size").click(b.doFunc);return $(".pte-confirm").live("click",function(){return d.doFunc()})};c=function(){var b;$("#pte-submit").click(function(){var a,c;c=q.getSelection();a=$("#pte-sizer").val();a={id:$("#pte-post-id").val(),action:"pte_ajax","pte-action":"resize-images","pte-sizes[]":$(".pte-size").filter(":checked").map(function(){return $(this).val()}).get(),
x:Math.floor(c.x1/a),y:Math.floor(c.y1/a),w:Math.floor(c.width/a),h:Math.floor(c.height/a)};log("===== RESIZE-IMAGES =====");log(a);if(isNaN(a.x)||isNaN(a.y)||isNaN(a.w)||isNaN(a.h))return alert(objectL10n.crop_submit_data_error),log("ERROR with submit_data and NaN's"),!1;q.setOptions({hide:!0,x1:0,y1:0,x2:0,y2:0});$("#pte-submit").attr("disabled",!0);$.getJSON(ajaxurl,a,b);return!0});return b=function(b){log("===== RESIZE-IMAGES SUCCESS =====");log(b);a.parseServerLog(b.log);if(null!=b.error&&null==
b.thumbnails)alert(b.error);else return $("#stage1").moveLeft(),$("#stage2").html($("#stage2template").tmpl(b)).moveLeft({callback:a.functions.pteVerifySubmitButtonHandler.doFunc}),!1}};h=function(){var b;$("#pte-confirm").live("click",function(){var a,c;c={};$("input.pte-confirm").filter(":checked").each(function(a,b){var d;d=$(b).val();return c[d]=$(b).parent().parent().find(".pte-file").val()});a={id:$("#pte-post-id").val(),action:"pte_ajax","pte-action":"confirm-images","pte-nonce":$("#pte-nonce").val(),
"pte-confirm":c};log("===== CONFIRM-IMAGES =====");log(a);return $.getJSON(ajaxurl,a,b)});return b=function(b){log("===== CONFIRM-IMAGES SUCCESS =====");log(b);a.parseServerLog(b.log);$("#stage2").moveLeft();$("#stage3").html($("#stage3template").tmpl(b)).moveLeft();return!1}};b=function(){var a,b;b=function(a){var b,c;null!=a&&a.preventDefault();a=null!=(b=null!=(c=a.data)?c.selector:void 0)?b:".pte-size";return $(a).filter(":checked").click()};a=function(a){var b,c;null!=a&&a.preventDefault();a=
null!=(b=null!=a?null!=(c=a.data)?c.selector:void 0:void 0)?b:".pte-size";return $(a).not(":checked").click()};$("#pte-selectors .all").click(a);$("#pte-selectors .none").click(b).click();$("#stage2").delegate("#pte-stage2-selectors .all","click",{selector:".pte-confirm"},a);$("#stage2").delegate("#pte-stage2-selectors .none","click",{selector:".pte-confirm"},b);return!0};return $.extend(a.functions,{iasSetAR:p})})(pte);
